### ISSUE TITLE
对于算法运行的一些疑惑

### ISSUE THREAD

**Issue by zhang-20222** [Rc-W024/SAR_Ship_detection_CFAR#1]
你好，我在复现您的代码的时候效果如下：

因为运行效果和您论文中的结果相差很大，请问您发布的这个代码是最初的CFAR目标检测代码吗
![CFAR_ship_detection](https://user-images.githubusercontent.com/103631031/163345028-06dba849-15fe-474e-9817-49f61b9de519.jpg)
？

**Comment by Rc-W024** [comment]
你好，

感谢你的关注和反馈！我上传的代码并不是一段完整的全自动化过程。

在运行代码之初，我遇到了输出颜色异常的类似问题，但由于论文时间紧凑，我没能及时解决这个问题，而是多写了一段代码将红色目标图像转换为二值图像（我没有上传这段代码，但编写难度不大）。在后续的讨论问题中我查找了Matlab图像颜色输出异常的有关资料，可能的问题与解决方案有很多种，但因为博士课题推进的缘故我没能继续解决这个遗留问题，希望你能有所突破。

对于检测结果，CFAR主要通过计算图像杂波分布模型来实现目标检测，其参数设定尤为重要，我的建议是在保持一个恒定虚警率的情况下（这种情况下我们默认背景与目标的分割效果达到预期），适当调整形态学滤波的参数，以实现精确检测。但如果图像背景较为复杂，同样可能导致目标检测失败。SAR目标检测是一个需要反复调参的过程，可能需要多次仿真实验才会达到任务预期。我上传的代码是一段基础算法（¡MUY
IMPORTANTE!），往往越简单、越基础的才是后期对研究有极大帮助的，我十分鼓励你在此基础上继续优化算法，或通过学习开发出更高阶、高效的算法。

如果后续有什么问题，我们再联络。
祝学习顺利！

070220zhang ***@***.***> 于2022年4月14日周四 10:25写道：

**Comment by zhang-20222** [comment]
Dear Ruochen：        
        您好~ 
        我是国防科技大学的一名在读硕士研究生，现在做的课题是航海雷达目标跟踪，但是网上相关资料很少
![微信图片_20220414170714](https://user-images.githubusercontent.com/103631031/163352824-6587a206-1ffc-4c9e-bf00-398b437d5eaf.png)

       在航海雷达目标检测方面，我找到的论文里面叙述代码效果的只有您的效果最优！！！
       仔细拜读了您的论文，请问您方便发我一份可以实现您论文中的代码吗？保证仅用于个人学术研究，且如若将来发表论文，一定做好对该论文的引用。
       此致，
敬礼！
Sinrecely,
Best regards.
Jiaju Zhang
