### ISSUE TITLE
对于代码中公式的疑惑

### ISSUE THREAD

**Issue by zenglang1** [Rc-W024/SAR_Ship_detection_CFAR#2]
博主，你好，我看了您的论文，跑了您的代码，很开心在您的代码中学习到很多的东西。
我有以下几个问题想请教一下博主：
1.代码中计算阈值th = (2*sqrt(-log(Pfa))-sqrt(pi))/(sqrt(4-pi))；我翻阅了很多资料也没有明白，通过查阅的文献，阈值的计算应该与拟合背景杂波的分布有关，博主用的瑞利分布，所以这个计算表达式是瑞利分布公式推算出来的吗？想请教一下博主这个公式从何而来？
2.在Iterate over each point in the image （迭代图像中的每个点）中，博主使用到的 temp = (g(i,j)-u)/delta;  u是平均值，delta是方差，这个判别式是正态分布的？瑞利分布也可以用这样的判别式吗？
如果问了一些傻瓜问题，还请博主见谅，期待博主的回复，谢谢

**Comment by Rc-W024** [comment]
你好！

感谢你的关注和反馈！

对于第一个问题，你的想法是没错的，阈值的计算取决于图像杂波分布模型。对于SAR图像，瑞利分布能够对图像中的均值区域更好的建模，此外，它还能较好地与海杂波分布拟合。为了获取检测阈值，需要将分布模型的表达式代入CFAR检测算子中得到阈值公式，主要包括形状参数、杂波强度等参数。不同分布模型，检测器阈值计算也不
同。对于第二个问题，双参数CFAR利用背景的均方差和均值来检测目标，将被检测像素点与背景的均值和方差比较，超出阈值的就被判别为潜在目标。起初算法要求雷达回波需要满足高斯分布，但在实际实验中，不同SAR图像背景分布模型均可适用，尤其是海面舰船检测。同时该方法效率高、计算简单，故有很广泛的应用。

希望草率的回答能够帮到你一些。

祝好！

zenglang1 ***@***.***> 于2022年5月18日周三 11:20写道：

**Comment by zenglang1** [comment]
谢谢博主的耐心回答
