### ISSUE TITLE
完全不work

### ISSUE THREAD

**Issue by aiboys** [Rc-W024/SAR_Ship_detection_CFAR#3]
hi
作者你好。有将这个代码运行在SSDD和HRSID数据集上验证，效果很差，几乎是等于完全不work的程度，但是你给的几个图片测试效果看起来是能work的，虽然精度不高，但至少感觉是work的。想知道为什么呢？

**Comment by Rc-W024** [comment]
你好，

所上传的代码不是一套全是动画检测流程，需要根据实际情况对部分参数（如窗口尺寸、形态学滤波等）进行调整。因此上传的部分可用于学习、理解，并不能完全应用于任何场景直接检测。

感谢您的专注，祝顺利！

aiboys ***@***.***> 于2022年8月26日周五 16:27写道：
